name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        poetry-version: [1.1.2]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.1.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies
        run: |
          poetry install
      - name: Run flake8
        run: |
          poetry run python -m flake8 --count --select=E9,F63,F7,F82 --show-source --statistics 
          poetry run python -m flake8 --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Run pytest
        run: |
          poetry run python -m pytest tests/
      - if: github.event_name == 'push'
        name: Publish
        env:
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
        run: |
          poetry publish --build --no-interaction -vv --username $PYPI_USERNAME --password $PYPI_PASSWORD
#      - if: github.event_name == 'push'
#        name: Generate release
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: npx semantic-release

