name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9, 3.10]
        poetry-version: [1.1.13]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.1.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies
        run: |
          poetry install
      - name: Run flake8
        run: |
          poetry run python -m flake8 --count --select=E9,F63,F7,F82 --show-source --statistics 
          poetry run python -m flake8 --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Run pytest
        run: |
          poetry run python -m pytest tests/
  publish_pypi:
    name: Publish on pypi
    needs: ci
    if: github.event_name == 'push' 
    env:
      PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: Run image
        uses: abatilo/actions-poetry@v2.1.0
        with:
          poetry-version: 1.1.13
      - name: Install dependencies
        run: |
          poetry install
      - name: Publish on pypi
        run: |
          poetry publish --build --no-interaction -vv --username $PYPI_USERNAME --password $PYPI_PASSWORD